// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8n52kYdNZSB_Ydn-n1NQvCb91AnA0Auk',
    appId: '1:316929849470:web:48a19cbc83cef7c488002f',
    messagingSenderId: '316929849470',
    projectId: 'flutterfinal-edcd3',
    authDomain: 'flutterfinal-edcd3.firebaseapp.com',
    databaseURL: 'https://flutterfinal-edcd3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfinal-edcd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsT5U3immydF4wTgYy8azOMHccFwNRDec',
    appId: '1:316929849470:android:d6a80ae4b9a1ffe288002f',
    messagingSenderId: '316929849470',
    projectId: 'flutterfinal-edcd3',
    databaseURL: 'https://flutterfinal-edcd3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfinal-edcd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MeHddE8hE6c9Y1M9-miIUR6di4RDpkQ',
    appId: '1:316929849470:ios:45c2334011d2089688002f',
    messagingSenderId: '316929849470',
    projectId: 'flutterfinal-edcd3',
    databaseURL: 'https://flutterfinal-edcd3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfinal-edcd3.appspot.com',
    iosBundleId: 'com.example.meditationAppFlutterfinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MeHddE8hE6c9Y1M9-miIUR6di4RDpkQ',
    appId: '1:316929849470:ios:45c2334011d2089688002f',
    messagingSenderId: '316929849470',
    projectId: 'flutterfinal-edcd3',
    databaseURL: 'https://flutterfinal-edcd3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfinal-edcd3.appspot.com',
    iosBundleId: 'com.example.meditationAppFlutterfinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8n52kYdNZSB_Ydn-n1NQvCb91AnA0Auk',
    appId: '1:316929849470:web:201c0d19dbb33e3e88002f',
    messagingSenderId: '316929849470',
    projectId: 'flutterfinal-edcd3',
    authDomain: 'flutterfinal-edcd3.firebaseapp.com',
    databaseURL: 'https://flutterfinal-edcd3-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfinal-edcd3.appspot.com',
  );
}
